### ISSUE TITLE
Cross ScalaJS Versions

### ISSUE THREAD

**Issue by sorenbug** [portable-scala/sbt-crossproject#114]
I'd like to be able to publish for SJS 0.6 and 1.0.

**Comment by sjrd** [comment]
You can use sbt-crossproject 0.6.x with Scala.js 1.x as much as 0.6.x. It's written right at the beginning of the readme.

**Comment by sorenbug** [comment]
Of course, but I'd like to be able to share the same code between both versions of ScalaJS. @sjrd 

Something like
```scala
crossProject(JSProject, ...)
  .crossJSVersions("0.6.28", "1.0.0-M8")
```

**Comment by sjrd** [comment]
Oh, that won't ever be possible with sbt-crossproject. But you can have a look at https://github.com/sjrd/sbt-dynscalajs instead.
