### ISSUE TITLE
sbt version 1.13.17 in the readme

### ISSUE THREAD

**Issue by elyphas** [portable-scala/sbt-crossproject#124]
sorry, It must be 1.13.7 instead of 1.13.17?

I had trouble to compile with 1.13.17

**Comment by sjrd** [comment]
Probably 0.13.17.

1.2.1+ will work too.

**Comment by sjrd** [comment]
I looked for 1.13.17 in the readme but couldn't find it.

**Comment by elyphas** [comment]
sorry you're right I apologize
