### ISSUE TITLE
Classpath for JS project includes Java JARs too

### ISSUE THREAD

**Issue by hsn10** [portable-scala/sbt-crossproject#128]
I have simple sbt file: https://gitlab.com/hsn10/getopt/-/blob/ff15088ff1f327c3460cf2a7acc23b059aa64c1d/build.sbt with once dependency - scalatest

classpath for _getoptJS_ is constructed incorrectly. It includes both JVM and JS JARs of scalatest.

**Comment by sjrd** [comment]
Your build is misconfigured. Please remove `ThisBuild /` from `ThisBuild / libraryDependencies`

**Comment by hsn10** [comment]
that fixed problem with getoptJS and getoptJVM classpath. There is an another problem.

As I understand there are 3 projects: _getopt_ -> master and _getoptJS_ and _getoptJVM_ subprojects. After suggested fix sbt tries to compile _getopt_ for JVM now without any scalatest library which fails and both subprojects with their own version of scalatest which works.

It should not compile master to \target\ at all
```
sbt:getopt> getopt/compile
[info] Compiling 2 Scala sources to C:\Users\hsn\Documents\workspace\scala\getopt\target\scala-2.12\classes ...
[info] Compiling 2 Scala sources to C:\Users\hsn\Documents\workspace\scala\getopt\.js\target\scala-2.12\classes ...
[info] Compiling 2 Scala sources to C:\Users\hsn\Documents\workspace\scala\getopt\.jvm\target\scala-2.12\classes ...
```

I reworked build file using root and aggregate(getopt.js, getopt.jvm) as described there: https://www.scala-js.org/doc/project/cross-build.html but if I do root/compile it still compiles root project into target/ I think root should be pure aggregation - does not compile anything.

**Comment by sjrd** [comment]
Please see https://github.com/portable-scala/sbt-crossproject/issues/122#issuecomment-604480966

**Comment by hsn10** [comment]
what works for both root/compile and root/test is in root project.settings ( skip in compile := true )

It would be good to add it to documentation.
