### ISSUE TITLE
crossProject.withId

### ISSUE THREAD

**Issue by Sciss** [portable-scala/sbt-crossproject#129]
When converting from "plain" sbt, like

    lazy val geom = project.withId("lucre-geom").in(file("geom"))

to cross-project

    lazy val geom = crossProject(JSPlatform, JVMPlatform).withId("lucre-geom").in(file("geom"))

this fails with

>  error: value withId is not a member of sbtcrossproject.CrossProject.Builder

Is there a work-around?

**Comment by sjrd** [comment]
```scala
lazy val geom = CrossProject("lucre-geom", file("lucre-geom"))(JSPlatform, ...)...
```
You may have to explicitly import `CrossProject`.
