### ISSUE TITLE
Shared unmanaged jar

### ISSUE THREAD

**Issue by ip9dis** [portable-scala/sbt-crossproject#135]
Hello

I have an jar file which I want to import but I cannot seem to get it to work. The Scala project structure looks a bit like this (you can find the complete project [here](https://github.com/scala-loci/scala-loci)):
```
+build.sbt
+scala-loci-lang
  ++js
  ++jvm
  ++shared/src/main/scala/loci/runtime/FILE_WHERE_I_WANT_TO_IMPORT.scala
```
Now, when I use the scala REPL all I have to do to execute this jar basically is
```
:require lambda-rest-service-0.2.0-prealpha.jar
import org.springframework.boot.loader._
JarLauncher.main(Array[String]())
```
Sources online say that to do the same in file I need to place my jar in a lib folder. So I did that and I have tried to place the lib folder in numerous locations as well because of the structure of this Scala project but I cannot import the same way. When I place the lib folder in the jvm folder I can see that the jar is in the classpath but import tells me that springframework is not part of org package.
```
[info] lociLangJVM / Compile / unmanagedClasspath
[info]  List(Attributed(/home/ip9dis/Projects/scala-loci/scala-loci-lang/jvm/lib/lambda-rest-service-0.2.0-prealpha.jar))
```
What am I supposed to do when I need the shared folder to has access to this jar file though?
The sbt.build part looks like this although the complete file can be found again [here](https://github.com/scala-loci/scala-loci)
```
lazy val lociLang = (crossProject(JSPlatform, JVMPlatform)
  crossType CrossType.Full
  in file("scala-loci-lang")
  settings (normalizedName := "scala-loci-lang",
            SourceGenerator.remoteSelection,
            retypecheckRepo, retypecheck,
            macroparadise, macrodeclaration, scribe, scalatest)
  dependsOn lociCommunication % "compile->compile;test->test")

lazy val lociLangJVM = lociLang.jvm
lazy val lociLangJS = lociLang.js
```
I've tried inserting setting for the unmanagedBase but with no luck again.

**Comment by sjrd** [comment]
Hello,

This looks like a question on using sbt-crossproject, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.
