### ISSUE TITLE
Unable to fix projectDir depreciation for custom sbtcrossproject.CrossType

### ISSUE THREAD

**Issue by mdedetrich** [portable-scala/sbt-crossproject#143]
I am trying to remove the SBT (along with its plugins) depreciation warnings and I came across one that I am not sure how to proceed with.

Quill defines its own custom `sbtcrossproject.CrossType` as can be seen here https://github.com/getquill/quill/blob/master/build.sbt#L144-L176 and I am getting depreciation warnings for `def projectDir(crossBase: File, projectType: String): File` (its saying I should replace it with `platformDir`).

I however don't see how its possible to solve this depreciation warning since you kind of need to implement all of the methods, even in sbtcrossproject itself (see https://github.com/portable-scala/sbt-crossproject/blob/a92185d5c87f7437e74c1e994921dcb44e24b1cc/sbt-crossproject/src/main/scala/sbtcrossproject/CrossType.scala#L59-L125, you are also implementing/using the deprecated members) or am I missing something here?

**Comment by sjrd** [comment]
I don't understand. We only implement the deprecated method, but we don't use it. That shouldn't cause deprecation warnings. It seems you're doing the same. What is the deprecation that you get and about what exact like of code?

**Comment by mdedetrich** [comment]
So at least in the Intellij IDEA editor, even just implementing a `@deprecated` shows up as a depreciation warning

![image](https://user-images.githubusercontent.com/2337269/124383661-ebf46180-dccd-11eb-8931-1ea83f1103b3.png)

Maybe its just an Intellij IDEA issue? In any case if you are deprecating a method that's in an interface, doesn't it make sense to provide a default implementation for that deprecated method/function (which typically uses the new non deprecated methods/functions) so that you don't need to implement deprecated methods (not sure if this is possible in this situation though)?

**Comment by sjrd** [comment]
> Maybe its just an Intellij IDEA issue?

Looks like it, yes. The Scala compiler does not complain about that. You might be able to work around the issue by marking your implementation as `@deprecated` itself.

> In any case if you are deprecating a method that's in an `trait`/`abstract class`, doesn't it make sense to provide a default implementation for that deprecated method/function (which typically uses the new non deprecated methods/functions) so that you don't need to implement deprecated methods (not sure if this is possible in this situation though)?

It is not possible in this case.

**Comment by mdedetrich** [comment]
Cool thanks, I will report this upstream to Intellij and close the issue here.
