### ISSUE TITLE
Configuration dependencies between platforms

### ISSUE THREAD

**Issue by shishkin** [portable-scala/sbt-crossproject#144]
I know this might not be what sbt-crossproject is designed for, but I'd like to misuse it to have a JVM module task to use task outputs from a JS module. Concretely, generate Scala object with constants in JVM project based on the JS linked modules output and introspection of JSExport annotations in JS project.

Currently I run into issues of circular dependencies. Does anyone have a suggestion how this might be achieved? I know how to do it without crossproject, but would like to potentially share some code between modules as well.

**Comment by sjrd** [comment]
> I know how to do it without crossproject, but would like to potentially share some code between modules as well.

Not using sbt-crossproject is the right way to do this. Add
```scala
Compile / unmanagedSourceDirectories += pathToSharedSources
```
in your settings instead.

You're trying to use sbt-crossproject for only that setting, and then fighting against everything else it does. You can spare yourself that pain. 😉
