### ISSUE TITLE
Release plugin powered with the new Scala Native `0.4.8`

### ISSUE THREAD

**Issue by danicheg** [portable-scala/sbt-crossproject#149]
The current version of the plugin (`1.2.0`) is built with Scala Native `0.3.7`. It turns out, `0.3.7` isn't binary compatible with `0.4.8`. So that leads to eviction errors on updating Scala Native version:
https://github.com/http4s/http4s/actions/runs/3431597047/jobs/5719913432#step:6:295
https://github.com/typelevel/cats/actions/runs/3431588068/jobs/5719889184#step:10:18
To workaround the issue, one could ignore these errors like this:
```
ThisBuild / libraryDependencySchemes += "org.scala-native" % "sbt-scala-native" % "always"
```
But generally speaking, it's not that wise. 
Can we get a new release of the `sbt-scala-native-crossproject` plugin?

**Comment by sjrd** [comment]
See https://github.com/portable-scala/sbt-crossproject/pull/148
