### ISSUE TITLE
Support multiple scala-js/scala-native versions

### ISSUE THREAD

**Issue by mdedetrich** [portable-scala/sbt-crossproject#47]
Not sure if this is currently possible, but it would be great if sbt-crossproject could support multiple versions of scala-js and scala-native at once.

Personal use case is https://github.com/mdedetrich/scalajson, and I would like to support scala-js 0.6.18 and the new scala-js 1.0.0x (and also in general for scala-native various releases)

**Comment by sjrd** [comment]
That's not possible. Please follow the instructions for cross-compilation in the release notes of Scala.js 1.0.0-M1, at https://www.scala-js.org/news/2017/07/03/announcing-scalajs-1.0.0-M1/#enabling-sbt-crossproject-even-with-scalajs-06x

If it were at all possible, you can imagine that I would have made it work.

**Comment by mdedetrich** [comment]
I understand its not possible now, is it something planned to be possible at some point?

**Comment by sjrd** [comment]
No it's not planned and won't be possible at any point. Again, if it were at all possible to make it eventually possible, I would have done so already.

**Comment by mdedetrich** [comment]
So how exactly are we meant to handle cross compiling against multiple scala.js/scala-native versions, I assume we have to resort to something like a bash script to manually override build files or to explore other options?

**Comment by sjrd** [comment]
It's all explained here: https://www.scala-js.org/news/2017/07/03/announcing-scalajs-1.0.0-M1/#cross-building-for-scalajs-06x-and-1x

**Comment by mdedetrich** [comment]
Okay thanks, will also probably have to do the same with scala-native

**Comment by sjrd** [comment]
Another possibility is to use [sbt-dynscalajs](https://github.com/sjrd/sbt-dynscalajs) and a similar solution for Scala Native.

In any case, the design of sbt-crossproject is completely antithetical to supporting several versions of the platform plugins. If someone wants to tackle this, they should either use the environment variables or sbt-dynscalajs or come up with their own solution.
