### ISSUE TITLE
Plugins can only be enabled for all of the projects

### ISSUE THREAD

**Issue by eatkins** [portable-scala/sbt-crossproject#75]
There are a number of plugins that only make sense on a particular platform (e.g. ScalaJSBundlerPlugin). Enabling them on a cross project, makes them active on all projects. This can completely break the incompatible projects. As a workaround, I've had to make separate projects and symlink shared source code in managedSources.

**Comment by sjrd** [comment]
The standard way to do anything specifically on one platform (besides settings) is to use `.xyzConfigure`. For example,
```scala
lazy foo = crossProject
  .jsConfigure(_.enablePlugins(ScalaJSBundlerPlugin))
  .settings(
    ...
  )
```

**Comment by eatkins** [comment]
Aah, ok. It would be great to add this to the README.md.
