### ISSUE TITLE
Strange Issues in IntelliJ on Mac

### ISSUE THREAD

**Issue by darkfrog26** [portable-scala/sbt-crossproject#85]
Okay, this is a very specific and odd issue.  Now, I recognize this is most likely a bug in IntelliJ's Scala plugin and not sbt-crossproject, but since it's specific to sbt-crossproject causing it, I'm hoping you all might know a solution.

On my MacBook Pro I'm experiencing this, but not on my Ubuntu desktop. I've completely cleared existing settings and wiped everything only to have the exact same issue come back.

<img width="1680" alt="screen shot 2018-03-18 at 8 31 26 pm" src="https://user-images.githubusercontent.com/877534/37573993-5f629562-2aeb-11e8-8073-1e4e1fe4ee6b.png">

IntelliJ warns me that `Some[String]` doesn't conform to the expected type of `Option[String]`. If I investigate by going to the `Option` definition, I get Scala Native's implementation, but going to `Some` I get see the standard Scala JVM version.  IntelliJ seems to be getting confused about which jars to utilize.  What's even more strange is that this is *only* on my MacBook Pro.  This same project on Ubuntu has no problems at all.

You are more than welcome to check out the project to see it: https://github.com/outr/scribe

**Comment by darkfrog26** [comment]
To be clear here, the project still compiles and everything works fine within SBT.

**Comment by sjrd** [comment]
Looks like https://github.com/scala-native/scala-native/issues/1007, which is a Scala Native issue, not an sbt-crossproject issue.

**Comment by darkfrog26** [comment]
@sjrd ah, thanks. I'll follow that thread for a solution.
